name: Keep Tevi App Alive

on:
  schedule:
    - cron: "*/15 * * * *"   # cada 15 minutos
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Tevi App
        run: curl -s https://tevi-app-citas-udea.streamlit.app || true
